### ISSUE TITLE
Change app name to something other than "shard"

### ISSUE THREAD

**Issue by arapawa** [dannytpeck/shiny-stone#4]
Changing to Shiny Stone

**Comment by arapawa** [comment]
- [ ] Change Title and related stuff in .html
- [ ] Host in new folder on the server
- [ ] Redirect luminous-shard to shiny-stone
- [ ] Change github repo name in project and README.md @dannytpeck

**Comment by dannytpeck** [comment]
Resolved in 5cc09ae
